import { AlexandriaTokens } from '../styles/tokens'
import type { BookVolumeSpec } from '../components/spatial/BookCoverMesh'

const asset = (path: string) => `${import.meta.env.BASE_URL}covers/${path}`

/** Canonical five — Foundations of the West */
export const CANON: BookVolumeSpec[] = [
  {
    id: 'bible-kjv',
    title: 'The Holy Bible',
    subtitle: 'Old & New Testaments',
    author: 'Canonical Assembly',
    bindingColor: AlexandriaTokens.bindings.oxblood,
    foilKey: 'antiqueGold',
    motif: 'chi-ro-border',
    coverArt: {
      front: asset('cover-bible-front.jpg'),
      spine: asset('cover-bible-spine.jpg'),
    },
    width: 0.4,
    height: 0.66,
    depth: 0.085,
    gutenbergId: 10,
    blurb:
      'The book that taught the English-speaking world how to speak of God, law, and conscience.',
    readerTheme: {
      ink: AlexandriaTokens.paper.inkPrimary,
      paper: AlexandriaTokens.paper.vellumWarm,
      accent: AlexandriaTokens.foils.antiqueGold.base,
      measureCh: 58,
      dropCaps: true,
    },
  },
  {
    id: 'plato-republic',
    title: 'The Republic',
    subtitle: 'Translated by Benjamin Jowett',
    author: 'Plato',
    bindingColor: AlexandriaTokens.bindings.oliveCloth,
    foilKey: 'polishedBrass',
    motif: 'palmette',
    coverArt: {
      front: asset('cover-republic-front.jpg'),
      spine: asset('cover-republic-spine.jpg'),
    },
    width: 0.42,
    height: 0.63,
    depth: 0.068,
    gutenbergId: 1497,
    blurb: 'Justice argued until the city becomes a soul — the West’s longest conversation on the good life.',
    readerTheme: {
      ink: '#101820',
      paper: '#eef2f0',
      accent: AlexandriaTokens.foils.polishedBrass.base,
      measureCh: 60,
      dropCaps: true,
    },
  },
  {
    id: 'aristotle-ethics',
    title: 'Nicomachean Ethics',
    subtitle: 'Translated by W. D. Ross',
    author: 'Aristotle',
    bindingColor: AlexandriaTokens.bindings.deepUltramarine,
    foilKey: 'burnishedCopper',
    motif: 'concentric',
    coverArt: {
      front: asset('cover-ethics-front.jpg'),
      spine: asset('cover-ethics-spine.jpg'),
    },
    width: 0.41,
    height: 0.62,
    depth: 0.07,
    gutenbergId: 8438,
    blurb: 'Happiness as activity of the soul in accordance with virtue — the grammar of practical reason.',
    readerTheme: {
      ink: '#10141c',
      paper: '#eef1f6',
      accent: AlexandriaTokens.foils.burnishedCopper.base,
      measureCh: 60,
      dropCaps: true,
    },
  },
  {
    id: 'aurelius-meditations',
    title: 'Meditations',
    subtitle: 'Translated by George Long',
    author: 'Marcus Aurelius',
    bindingColor: AlexandriaTokens.bindings.antiqueBlack,
    foilKey: 'antiqueGold',
    motif: 'laurel',
    coverArt: {
      front: asset('cover-meditations-front.jpg'),
      spine: asset('cover-meditations-spine.jpg'),
    },
    width: 0.38,
    height: 0.58,
    depth: 0.055,
    gutenbergId: 2680,
    blurb: 'An emperor’s private notes on duty, mortality, and the citadel of the self.',
    readerTheme: {
      ink: '#141416',
      paper: '#f4efe6',
      accent: AlexandriaTokens.foils.antiqueGold.base,
      measureCh: 56,
      dropCaps: true,
    },
  },
  {
    id: 'homer-iliad',
    title: 'The Iliad',
    subtitle: 'Translated by Samuel Butler',
    author: 'Homer',
    bindingColor: AlexandriaTokens.bindings.seaSlate,
    foilKey: 'silverWave',
    motif: 'wave-anchor',
    coverArt: {
      front: asset('cover-iliad-front.jpg'),
      spine: asset('cover-iliad-spine.jpg'),
    },
    width: 0.43,
    height: 0.64,
    depth: 0.075,
    gutenbergId: 6130,
    blurb: 'Rage, honor, and the cost of glory — the first great Western poem of war.',
    readerTheme: {
      ink: '#101820',
      paper: '#e8eef2',
      accent: AlexandriaTokens.foils.silverWave.base,
      measureCh: 60,
      dropCaps: true,
    },
  },
]
